[app]
address = "0.0.0.0:9000"
admin_username = "admin"
admin_password = "listmonk-dev-123"

[db]
host = "postgres"
port = 5432
user = "blogadmin"
password = "blogdev123"
database = "listmonk"
ssl_mode = "disable"
max_open = 25
max_idle = 25
max_lifetime = "300s"
