# syntax=docker/dockerfile:1
FROM ghcr.io/maxmind/geoipupdate:v8.0.0-amd64

LABEL org.opencontainers.image.title="lzocateli/geoipupdate" \
  org.opencontainers.image.description="Container geoipupdate baseado em MaxMind para atualizar bases de dados GeoIP2 de forma agendada." \
  org.opencontainers.image.source="https://github.com/lzocateli/containers" \
  org.opencontainers.image.documentation="https://github.com/lzocateli/containers/tree/main/geoipupdate" \
  org.opencontainers.image.url="https://github.com/lzocateli/containers/tree/main/geoipupdate" \
  org.opencontainers.image.version="8.0.0"