# syntax=docker/dockerfile:1
FROM ghcr.io/immich-app/immich-machine-learning:v3.2.4@sha256:e16c2f166a8174901959fdf85e2e4c7bd1ebc4b37e0b6655de97c41408a260c4

LABEL org.opencontainers.image.title="lzocateli/immich-ml" \
  org.opencontainers.image.description="Espelho do machine learning Immich v3.2.4 (CPU) para o TrueNAS." \
  org.opencontainers.image.source="https://github.com/lzocateli/containers" \
  org.opencontainers.image.documentation="https://github.com/lzocateli/containers/tree/main/immich-ml" \
  org.opencontainers.image.url="https://github.com/lzocateli/containers/tree/main/immich-ml" \
  org.opencontainers.image.version="v3.2.4"