version: "3.8"


services:


  pihole:
    container_name: pihole
    image: lzocateli/pihole:2024.07.0
    restart: unless-stopped
    hostname: pi.hole
    depends_on:
#      - cloudflared
      - unbound
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      # - "67:67/udp"
      - "80:80/tcp"
      # - "443:443/tcp"
    environment:
      TZ: 'America/Sao_Paulo'
      WEBPASSWORD_FILE: #'/run/secrets/pihole'
      PIHOLE_DNS_: '127.0.0.1'
      PIHOLE_DNS_: '172.16.10.52#5053'
      DNSMASQ_LISTENING: 'all'
      VIRTUAL_HOST: 'pi.hole'
      PROXY_LOCATION: 'pi.hole'
      FTLCONF_LOCAL_IPV4: '127.0.0.1'
      FTLCONF_LOCAL_IPV6: 'fd28:fd43:c2c2::f78'
    volumes:
      - /userapps/vol-pihole/etc/pihole/99-edns.conf:/etc/pihole/99-edns.conf
      - /userapps/vol-pihole/etc/pihole:/etc/pihole
      - /userapps/vol-pihole/etc/dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
#    secrets:
#      - source: pihole
#        target: /run/secrets/pihole
    networks:
      dns_net:
        ipv4_address: 172.16.10.51


  unbound:
    container_name: unbound
    image: lzocateli/unbound:1.20.0
    restart: unless-stopped
    ports:
      - "5053:53/tcp"
      - "5053:53/udp"
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - /userapps/vol-pihole/etc/unbound:/opt/unbound/etc/unbound
      - /userapps/var/log/unbound:/var/log/unbound
    networks:
      dns_net:
        ipv4_address: 172.16.10.52


networks:
  dns_net:
    driver: bridge
#    ipam:
#        config:
#        - subnet: 172.16.53.0/29
    name: dns_net
#  proxy:
#    external: true

#172.16.53.1 - 172.16.53.6
#255.255.255.248
#172.16.53.0/29

secrets:
  pihole:
    external: true
