# syntax=docker/dockerfile:1

FROM certbot/dns-cloudflare:v5.7.0

ARG IMAGE_VERSION="5.7.0"

LABEL org.opencontainers.image.title="lzocateli/certbot-dns-cloudflare" \
	org.opencontainers.image.description="Certbot com plugin DNS Cloudflare para emissão e renovação de certificados Let's Encrypt via desafio DNS-01." \
	org.opencontainers.image.source="https://github.com/lzocateli/containers" \
	org.opencontainers.image.documentation="https://github.com/lzocateli/containers/tree/main/certbot" \
	org.opencontainers.image.url="https://github.com/lzocateli/containers/tree/main/certbot" \
	org.opencontainers.image.version="${IMAGE_VERSION}"