FROM dbeaver/cloudbeaver:24.0.2

WORKDIR /opt/cloudbeaver

ADD https://repo1.maven.org/maven2/net/snowflake/snowflake-jdbc/3.14.5/snowflake-jdbc-3.14.5.jar /opt/cloudbeaver/drivers/

EXPOSE 8978
