version: "3.8"
services:
  rclone-msonedrive:
    restart: unless-stopped
    image: lzocateli/rclone-onedrive:1.0.0
    container_name: rclone-lzocateli
    environment:
      - RCLONE_DEST=onedrivelzocateli:/
      - TZ=America/Sao_Paulo
    volumes:
      - /mnt/cybertron/configs/userapps/var/log/onedrivelzocateli:/var/log/onedrivelzocateli
      - /mnt/cybertron/configs/userapps/utils:/userapps/utils
      - /mnt/cybertron/configs/userapps/utils/cronjobs:/etc/crontabs/root
      - /mnt/cybertron/configs/rclone:/config/rclone
      - /mnt/cybertron/lzocateli/onedrive:/data
    networks:
      - dockge_default
networks:
  dockge_default:
    external: true



    

# services:
#   rclone-lzocateli:
#     container_name: rclone-lzocateli
#     restart: unless-stopped
#     tty: true
#     environment:
#       - TZ=${TZ}
#       - RCLONE_DEST=onedrivelzocateli:/nas-backup
#     volumes:
#       - /mnt/cybertron/configs/rclone:/config/rclone:rw
#       - /mnt/cybertron/lzocateli/onedrive:/data:ro
#     build: .

  # rclone-maria:
  #   container_name: rclone-maria
  #   restart: unless-stopped
  #   tty: true
  #   environment:
  #     - TZ=${TZ}
  #     - RCLONE_DEST=onedrivemaria:/nas-backup
  #   volumes:
  #     - ${DOCKER_APPDATA_ROOT}/backup/rclone:/config/rclone:rw
  #     - ${BACKUP_DATA_ROOT}/Maria:/data:ro
  #   build: .
