version: "3.8"
services:
  rclone-msonedrive:
    restart: unless-stopped
    image: lzocateli/rclone-onedrive:1.0.0
    container_name: rclone-lzocateli
    environment:
      - RCLONE_DEST=onedrivelzocateli:/
      - LOG_FILE_NAME=onedrivelzocateli
      - TZ=America/Sao_Paulo
    volumes:
      - /mnt/cybertron/configs/userapps/var/log/onedrivelzocateli:/var/log/${LOG_FILE_NAME}
      - /mnt/cybertron/configs/userapps/utils/cronjobs:/etc/crontabs/root
      - /mnt/cybertron/configs/userapps/utils/start.sh:/userapps/utils/start.sh
      - /mnt/cybertron/configs/rclone:/config/rclone
      - /mnt/cybertron/lzocateli/onedrive:/data
    networks:
      - dockge_default
      
  rclone-msonedrive-grazi:
    restart: unless-stopped
    image: lzocateli/rclone-onedrive:1.0.0
    container_name: rclone-gsilveira
    environment:
      - RCLONE_DEST=onedrivegsilveira:/
      - LOG_FILE_NAME=onedrivegsilveira
      - TZ=America/Sao_Paulo
    volumes:
      - /mnt/cybertron/configs/userapps/var/log/onedrivegsilveira:/var/log/${LOG_FILE_NAME}
      - /mnt/cybertron/configs/userapps/utils/cronjobs:/etc/crontabs/root
      - /mnt/cybertron/configs/userapps/utils/start.sh:/userapps/utils/start.sh
      - /mnt/cybertron/configs/rclone:/config/rclone
      - /mnt/cybertron/gsilveira/onedrive:/data
    networks:
      - dockge_default
      
networks:
  dockge_default:
    external: true
