server {
    listen 443 default_server;
    listen [::]:443 default_server;
    server_name _;

    ssl_certificate       /etc/nginx/ssl/zocate.li.pem;
    ssl_certificate_key   /etc/nginx/ssl/zocate.li.key;

    include               /etc/nginx/conf.d/ssl-settings.conf;

    access_log /var/log/nginx/host.access.log main;
    error_log  /var/log/nginx/host.error.log;


    location / {
        internal;
    }

    include /etc/nginx/conf.d/custom-error.locations;

}

server {
    listen      80;
    listen      [::]:80;
    server_name _;


    location / {
        return 307 https://$request_uri;
    }

    include /etc/nginx/conf.d/custom-error.locations;

}
