#; Pi-hole FTL config file
#; Comments should start with #; to avoid issues with PHP and bash reading this file
MACVENDORDB=/macvendor.db
RATE_LIMIT=5000/60
PIHOLE_PTR=HOSTNAMEFQDN
LOCAL_DNS=true
LOCAL_IPV4=127.0.0.1

