# syntax=docker/dockerfile:1
FROM ghcr.io/immich-app/immich-server:v3.2.4@sha256:d317916b28090c33eb36b308464ea391f8b7df1d850fcfea227a39ec879718c2

LABEL org.opencontainers.image.title="lzocateli/immich-server" \
  org.opencontainers.image.description="Espelho do servidor Immich v3.2.4 para o TrueNAS." \
  org.opencontainers.image.source="https://github.com/lzocateli/containers" \
  org.opencontainers.image.documentation="https://github.com/lzocateli/containers/tree/main/immich-server" \
  org.opencontainers.image.url="https://github.com/lzocateli/containers/tree/main/immich-server" \
  org.opencontainers.image.version="v3.2.4"