server {
    listen 443 ssl;
    server_name seu_dominio.com;

    ssl_certificate /caminho/para/meucert.crt;
    ssl_certificate_key /caminho/para/meucert.key;

    location / {
        proxy_pass https://localhost:9090;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Necessário para o funcionamento dos websockets
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
