# syntax=docker/dockerfile:1
FROM ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23

LABEL org.opencontainers.image.title="lzocateli/immich-postgres" \
  org.opencontainers.image.description="Espelho do PostgreSQL 14 com VectorChord 0.4.3 e pgvectors 0.2.0 para Immich." \
  org.opencontainers.image.source="https://github.com/lzocateli/containers" \
  org.opencontainers.image.documentation="https://github.com/lzocateli/containers/tree/main/immich-postgres" \
  org.opencontainers.image.url="https://github.com/lzocateli/containers/tree/main/immich-postgres" \
  org.opencontainers.image.version="14-vc0.4.3-pgv0.2.0"